# Generated by Django 4.2.7 on 2023-11-15 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('IDalumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('fechaIngreso', models.DateField()),
                ('fechaEgreso', models.DateField(blank=True, null=True)),
                ('estadoAvance', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=25)),
                ('examenCand', models.BooleanField()),
                ('examenGrado', models.BooleanField()),
                ('institProcPreg', models.CharField(max_length=100)),
                ('institProcPostg', models.CharField(max_length=100)),
                ('tituloPregrado', models.CharField(max_length=100)),
                ('tituloPostgrado', models.CharField(max_length=100)),
                ('profGuia', models.CharField(max_length=100)),
                ('cotutela', models.BooleanField()),
                ('genero', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recursosBecas', models.IntegerField()),
                ('recursosPasantias', models.IntegerField()),
                ('recursosEventos', models.IntegerField()),
                ('recursosDisponibles', models.IntegerField()),
                ('recursosUtilizados', models.IntegerField()),
                ('recursosExternos', models.IntegerField()),
                ('año', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profDestino', models.CharField(max_length=100)),
                ('profOrigen', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('recursos', models.IntegerField()),
                ('beneficios', models.CharField(max_length=200)),
                ('institucionBeneficio', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvento', models.CharField(max_length=250)),
                ('año', models.DateField()),
                ('recursos', models.IntegerField()),
                ('institucion', models.CharField(max_length=100)),
                ('numEstudiantes', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBenef', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('recursos', models.IntegerField()),
                ('año', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.alumnos')),
            ],
        ),
    ]
